### ISSUE TITLE
\n new line

### ISSUE THREAD

**Issue by suntong** [lunet-io/scriban#10]
The `\n` [is supported in scriban](https://github.com/lunet-io/scriban/blob/master/doc/language.md#31-strings). So I assume the following will print new line instead of `\n` literal. will it not? 

            var template = Template.Parse(@"This is a \n{{ text }} World \nfrom scriban!");
            var result = template.Render(new { text = "Hello" });

Moreover, if the template string are complicated, then I got run-time exceptions. 

```
System.InvalidOperationException was unhandled
  HResult=-2146233079
  Message=This template has errors. Check the <Messages> property for more details
  Source=Scriban
  StackTrace:
       at Scriban.Template.Render(TemplateContext context)
       at Scriban.Template.Render(Object model)
       at Demo2.Program.Test2() in scDemo2.cs:line 76
       at ProgTest.Main(String[] args) in Main.cs:line 20
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

```

How to catch errors after `var template = Template.Parse`?

Sorry I'm not a seasoned C# developer.

**Comment by xoofx** [comment]
You are declaring a raw string `@"...."` which escaping the `\n` so isntead remove `@` in front of your string: 

```csharp
        var template = Template.Parse("This is a \n{{ text }} World \nfrom scriban!");
        var result = template.Render(new { text = "Hello" });
```

Also, if you have any errors when parsing, you need to check the errors before trying to render:

```csharp
var template = ...
if (template.HasErrors)
{
   foreach(var message in template.Messages) 
   {
          Console.WriteLine(message);
   }
   // exit/ throw an exception...etc.
}
```

**Comment by suntong** [comment]
Thanks A LOT for your help!

Just FTR, I've further nailed down my complicated template string as simple as this:

`var template = Template.Parse(@"This is a \n{{ text text ""\n"" text }} World \nfrom scriban!");
`

But looking at your existing test code, I realized that I should do this instead:

`var template = Template.Parse(@"This is a \n{{ text + text + ""\n"" + text }} World \nfrom scriban!");
`

or this, 

`var template = Template.Parse(@"This is a \n{{ text; text + ""\n"" + text }} World \nfrom scriban!");
`

Also, just FTR again, I need that `@"` because I'm using multi-line template strings in my code. So I replace them with `{{""\n""}}`, and it works fine. 

Thanks again for your help!
