### ISSUE TITLE
System.OverflowException for functions that have the TemplateContext and params as formal parameters

### ISSUE THREAD

**Issue by tatarincev** [lunet-io/scriban#104]
How to reproduce:
```C#
        public class MyFunctions
        {
            public static string T(TemplateContext context, object input, params object[] variables)
            {
                return input.ToString();
            }
        }
        [Fact]
        public void Function_With_Context_And_Params_Throw_Overflow_Exception()
        {
            var parsedTemplate = Template.ParseLiquid("{{ 'some resource key' | t }}");
            Assert.False(parsedTemplate.HasErrors);

            var scriptObject = new ScriptObject();
            scriptObject.Import(typeof(MyFunctions));
            var context = new TemplateContext();
            context.PushGlobal(scriptObject);

            parsedTemplate.Render(context);
          //throw System.OverflowException: 'Array dimensions exceeded supported range.'
        }
```
Exception stack
```
System.OverflowException
  HResult=0x80131516
  Message=Array dimensions exceeded supported range.
  Source=Scriban
  StackTrace:
   at Scriban.Runtime.GenericFunctionWrapper.Invoke(TemplateContext context, ScriptNode callerContext, ScriptArray arguments, ScriptBlockStatement blockStatement) in C:\tmp\scriban-master\src\Scriban\Runtime\GenericFunctionWrapper.cs:line 100
```
![image](https://user-images.githubusercontent.com/7566324/50634724-517a0280-0f58-11e9-9168-86493a8bd654.png)

UPD:
Change signature of function to 
```C#   
public static string T(object input, params object[] variables)
```
This template 
```LIQUID 
"{{ 'some resource key' | t }}"
``` 
throws 
```
Scriban.Syntax.ScriptRuntimeException
  HResult=0x80131500
  Message=Invalid number of arguments `1` passed to `t` while expecting `2` arguments
  Source=Scriban
  StackTrace:
   at Scriban.Runtime.GenericFunctionWrapper.Invoke(TemplateContext context, ScriptNode callerContext, ScriptArray arguments, ScriptBlockStatement blockStatement) in C:\Projects\VirtoCommerce\scriban\src\Scriban\Runtime\GenericFunctionWrapper.cs:line 197
```
Seems `params` looks as required argument, is right? Is possible to make it as optional?

**Comment by xoofx** [comment]
Thanks, this should be fixed by commit afe5378 and available in upcoming scriban `v2.0.0-alpha-004`
