### ISSUE TITLE
Problems with Version 3 IFormattable enhancement

### ISSUE THREAD

**Issue by klaasbrant** [lunet-io/scriban#267]
I often have a ToString method in our objects for error messages or easy debugging. Since version 3 I have a problem that when I have a IEnumerable<object> and the object has such a ToString method the {{ for x in object }} fails. Bug or feature? If this is a feature am I able to turn this check off so the for behaves like version 2?

**Comment by xoofx** [comment]
>  I often have a ToString method in our objects

I assume you are talking about your own .NET objects?

>  I have a problem that when I have a IEnumerable and the object has such a ToString method the {{ for x in object }} fails

Not sure to follow. Is it the `for` loop failing here, or the fact that later you are printing x and it doesn't work?

Could you provide a few lines Program.cs repro?

**Comment by klaasbrant** [comment]
The problem is not in the ToString but even more strange. I debugged until I could isolate the problem. Here is a small program:

namespace ConsoleApp1
{
    public class masterfile
    {
        public IEnumerable<DBColumn> columns { get; set; }
    }

    public class DBColumn
    {
        public string colname { get; set; }
        public char nulls { get; set; }
    }
    

    class Program
    {
        static void Main(string[] args)
        {
            masterfile m1 = new masterfile
            {
                columns = new List<DBColumn> { new DBColumn { colname = "one" }, new DBColumn { colname = "two" } }
            };
            Template tx1 = Template.Parse("{{ for col in columns }}{{ for.index }} Hello {{ col.nulls }} {{ end }}");
            string o1  = tx1.Render(m1);
            Console.ReadLine();
        }
    }
}

This gives in Version 3:

Scriban.Syntax.ScriptRuntimeException
  HResult=0x80131500
  Message=<input>(1,23) : error : Unable to cast object of type 'System.Char' to type 'System.IFormattable'.
  Source=Scriban
  StackTrace:
   at Scriban.TemplateContext.Evaluate(ScriptNode scriptNode, Boolean aliasReturnedFunction)
   at Scriban.Syntax.ScriptForStatement.LoopItem(TemplateContext context, LoopState state)
   at Scriban.Syntax.ScriptForStatement.EvaluateImpl(TemplateContext context)
   at Scriban.Syntax.ScriptLoopStatementBase.Evaluate(TemplateContext context)
   at Scriban.TemplateContext.Evaluate(ScriptNode scriptNode, Boolean aliasReturnedFunction)
   at Scriban.Syntax.ScriptBlockStatement.Evaluate(TemplateContext context)
   at Scriban.TemplateContext.Evaluate(ScriptNode scriptNode, Boolean aliasReturnedFunction)
   at Scriban.Syntax.ScriptPage.Evaluate(TemplateContext context)
   at Scriban.TemplateContext.Evaluate(ScriptNode scriptNode, Boolean aliasReturnedFunction)
   at Scriban.Template.EvaluateAndRender(TemplateContext context, Boolean render)
   at Scriban.Template.Render(TemplateContext context)
   at Scriban.Template.Render(Object model, MemberRenamerDelegate memberRenamer, MemberFilterDelegate memberFilter)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\kbran\source\repos\Scriban test\ConsoleApp1\Program.cs:line 32

  This exception was originally thrown at this call stack:
    Scriban.TemplateContext.ObjectToStringImpl(object, bool)
    Scriban.TemplateContext.ObjectToString(object, bool)
    Scriban.TemplateContext.Write(Scriban.Parsing.SourceSpan, object)
    Scriban.Syntax.ScriptBlockStatement.Evaluate(Scriban.TemplateContext)
    Scriban.TemplateContext.Evaluate(Scriban.Syntax.ScriptNode, bool)

Inner Exception 1:
InvalidCastException: Unable to cast object of type 'System.Char' to type 'System.IFormattable'.


BUT, if you change nulls to Nulls (anything different than lowercase nulls) the problem is gone. Problem does not occur on V2.
Strangely it complains about the {{for}}.  Are there reserved words like "nulls" ?

**Comment by xoofx** [comment]
This should be fixed in the next release `3.0.4`

**Comment by klaasbrant** [comment]
Thanks for the swift response. Scriban is awesome!
