### ISSUE TITLE
TargetParameterCountException when using a custom dictionary as the model

### ISSUE THREAD

**Issue by thomaslevesque** [lunet-io/scriban#62]
For various reasons, I'm using a custom `IDictionary<string, object>` implementation as the model, rather than a strongly-typed object. When I call `Render` on the template, I get the following exception:

```
System.Reflection.TargetParameterCountException
  HResult=0x8002000E
  Message=Parameter count mismatch.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Scriban.Runtime.ScriptObjectExtensions.Import(IScriptObject script, Object obj, ScriptMemberImportFlags flags, MemberFilterDelegate filter, MemberRenamerDelegate renamer)
   at Scriban.Runtime.ScriptObjectExtensions.Import(IScriptObject script, Object obj, MemberFilterDelegate filter, MemberRenamerDelegate renamer)
   at Scriban.Template.Render(Object model, MemberRenamerDelegate memberRenamer)
   at REDACTED.Mail.MailService.<SendEmailAsync>d__4.MoveNext() in C:\Projects\REDACTED\REDACTED\src\REDACTED.Mail\MailService.cs:line 49
```

The calling code looks like this:

```csharp
// templateInfo.Data is a normal Dictionary<string, object>
var data = new FallbackDictionary<string, object>(templateInfo.Data);
data["RecipientName"] = to.Name;
data["TenantName"] = _tenantContext.Tenant?.Name;
```

(it works fine if I use a normal `Dictionary<string, object>`)

`FallbackDictionary` is a dictionary that looks up missing keys in a fallback dictionary. The implementation is [here](https://gist.github.com/thomaslevesque/39e9b12f98a08859a4ebea65db33e72d). The goal is to avoid creating a copy of `templateInfo.Data` when I just want to add two values to it.

What could be causing the error?

I'm targeting netcoreapp2.1

**Comment by thomaslevesque** [comment]
Ah, it looks like I [have to implement the non-generic `IDictionary` interface](https://github.com/lunet-io/scriban/blob/master/src/Scriban/Runtime/ScriptObjectExtensions.cs#L56).

**Comment by xoofx** [comment]
Yeah, not sure Import is actually the right thing to use in your case as it copies the values. The top level object that is exposed to the runtime in the end is a `ScriptObject`. The only thing that would work is to set on this ScriptObject a property value equal directly to your dictionary, and it will go through a different object accessor (dictionary) [that is supporting generics](https://github.com/lunet-io/scriban/blob/master/src/Scriban/Runtime/Accessors/DictionaryAccessor.cs)

**Comment by thomaslevesque** [comment]
Thanks @xoofx. I ended up adding the content of my dictionary directly to the `ScriptObject`.
