### ISSUE TITLE
1.2.4 breaks in basic use case

### ISSUE THREAD

**Issue by dodyg** [lunet-io/scriban#69]
It breaks at `var output = parseTemplate.Render(model)`. I had to revert to 1.2.3.

```

        public (string subject, string content) Load(MailTemplate template, object model)
        {
            var templatePath = Path.Combine(_rootPath, template.TemplateFile);

            var templateContent = File.ReadAllText(templatePath);

            var parsedTemplate = Scriban.Template.Parse(templateContent);

            var output = parsedTemplate.Render(model);

            return (template.Subject, output);
        }
```

**Comment by thomaslevesque** [comment]
I can confirm this on .NET Core 2.1 (it seems to work on desktop .NET Framework, though). Even the most basic use case throws a `NullReferenceException`

Here's a repro:

```csharp
var template = Template.Parse("Welcome to {{name}}");
var templateData = new
{
    Name = "Foo"
};
Console.WriteLine(template.Render(templateData));
```

Here's the exception:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Scriban.Runtime.ScriptObjectExtensions.Import(IScriptObject script, Object obj, ScriptMemberImportFlags flags, MemberFilterDelegate filter, MemberRenamerDelegate renamer) in C:\projects\scriban\src\Scriban\Runtime\ScriptObjectExtensions.cs:line 245
   at Scriban.Runtime.ScriptObjectExtensions.Import(IScriptObject script, Object obj, MemberFilterDelegate filter, MemberRenamerDelegate renamer) in C:\projects\scriban\src\Scriban\Runtime\ScriptObjectExtensions.cs:line 63
   at Scriban.Template.Render(Object model, MemberRenamerDelegate memberRenamer, MemberFilterDelegate memberFilter) in C:\projects\scriban\src\Scriban\Template.cs:line 189
   at TestScriban.Program.Main(String[] args) in C:\tmp\TestScriban\Program.cs:line 15
```

The same code with Scriban 1.2.3 works fine on both .NET Core and .NET Framework.

**Comment by thomaslevesque** [comment]
Here's a gist with the full repro:

https://gist.github.com/thomaslevesque/c4c0fad9c0e47a664634a9c026cae848

**Comment by thomaslevesque** [comment]
I can confirm the problem is fixed in 1.2.5. Thanks!
