### ISSUE TITLE
Dynamic objects are not getting rendered

### ISSUE THREAD

**Issue by karayakar** [lunet-io/scriban#75]
public static string RenderTemplateByFilename(string filename, **dynamic obj**)
        {
            try
            {
                TemplateHolder t = GetTemplateByFileName(filename + ".html");
                var template = Template.Parse(t.TemplateCode);
                return template.Render( **obj** ); <----- Fails. 
            }
            catch (Exception ex)
            {
                return ex.Message;
            }

   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Scriban.Runtime.ScriptObjectExtensions.Import(IScriptObject script, Object obj, ScriptMemberImportFlags flags, MemberFilterDelegate filter, MemberRenamerDelegate renamer) in C:\projects\scriban\src\Scriban\Runtime\ScriptObjectExtensions.cs:line 267
   at Scriban.Runtime.ScriptObjectExtensions.Import(IScriptObject script, Object obj, MemberFilterDelegate filter, MemberRenamerDelegate renamer) in C:\projects\scriban\src\Scriban\Runtime\ScriptObjectExtensions.cs:line 64
   at Scriban.Template.Render(Object model, MemberRenamerDelegate memberRenamer, MemberFilterDelegate memberFilter) in C:\projects\scriban\src\Scriban\Template.cs:line 195
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at PresenTVCore.TemplateEngine.Model.TemplateModel.RenderTemplateByFilename(String filename, Object obj)

**Comment by xoofx** [comment]
Thanks @moh-hassan for the suggestion. I think it is better to go that route when using dynamic objects.
